CREATE TABLE citations (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id       varchar(20)   NOT NULL,
    zone             varchar(50)   NOT NULL,
    speed_kph        numeric(5,2)  NOT NULL,
    speed_limit_kph  numeric(5,2)  NOT NULL,
    excess_kph       numeric(5,2)  NOT NULL,
    fine_amount      numeric(12,2) NOT NULL,
    rule_set_version varchar(32)   NOT NULL,
    reason           varchar(255)  NOT NULL,
    observed_at      timestamptz   NOT NULL,
    recorded_at      timestamptz   NOT NULL,
    CONSTRAINT citations_over_limit_ck CHECK (speed_kph > speed_limit_kph)
);

CREATE INDEX citations_zone_id_idx ON citations (zone, id DESC);
