CREATE TABLE violations (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    fine_amount     integer          NOT NULL,
    recorded_at     timestamp(6) with time zone NOT NULL,
    speed_kph       double precision NOT NULL,
    speed_limit_kph double precision NOT NULL,
    vehicle_id      varchar(20)      NOT NULL,
    zone            varchar(50)      NOT NULL,
    CONSTRAINT violations_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_violations_zone ON violations (zone);
